In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('weather_data.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'weather_data.csv'

In [63]:
df1 = df[['name','precip','windspeed','conditions']]

In [64]:
df1

          name  precip  windspeed        conditions
0    Amsterdam     0.0        4.0             Clear
1    Amsterdam     0.0        6.9             Clear
2    Amsterdam     0.0        6.5  Partially cloudy
3    Amsterdam     0.0        6.7  Partially cloudy
4    Amsterdam     0.0        7.4  Partially cloudy
..         ...     ...        ...               ...
739  Amsterdam     0.0       21.3          Overcast
740  Amsterdam     0.0       21.3          Overcast
741  Amsterdam     0.0       20.8          Overcast
742  Amsterdam     0.0       18.4          Overcast
743  Amsterdam     0.0       20.4          Overcast

[744 rows x 4 columns]

In [65]:
df1['precip'].nlargest(n=40)

441    2.779
440    2.487
439    2.414
679    2.040
438    1.923
269    1.765
271    1.676
656    1.673
681    1.664
442    1.626
485    1.610
659    1.582
657    1.578
165    1.531
680    1.512
502    1.466
658    1.446
268    1.428
266    1.390
678    1.340
660    1.277
445    1.177
270    1.142
267    1.051
677    0.991
436    0.976
503    0.964
443    0.939
444    0.880
661    0.863
164    0.847
504    0.840
260    0.835
265    0.800
437    0.763
261    0.759
596    0.737
505    0.725
163    0.641
501    0.626
Name: precip, dtype: float64

In [66]:
df1['windspeed'].nlargest(n=25)

486    52.3
484    51.8
485    48.5
494    48.1
442    46.0
449    44.2
451    43.9
493    43.7
495    43.1
496    42.5
492    42.1
487    42.0
483    41.9
448    41.1
452    41.0
478    40.8
450    40.7
482    40.7
488    40.4
477    39.9
690    39.6
446    39.5
445    39.0
447    38.4
453    38.2
Name: windspeed, dtype: float64

In [67]:
df1['Wind_Cond'] = np.where(df['windspeed']>30,True,False)

C:\Users\sam50\AppData\Local\Temp\ipykernel_8840\3919901926.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Wind_Cond'] = np.where(df['windspeed']>30,True,False)

In [68]:
df1['Precip_Cond'] = np.where(df['precip']>1,True,False)

C:\Users\sam50\AppData\Local\Temp\ipykernel_8840\661300588.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Precip_Cond'] = np.where(df['precip']>1,True,False)

In [69]:
df1

          name  precip  windspeed        conditions  Wind_Cond  Precip_Cond
0    Amsterdam     0.0        4.0             Clear      False        False
1    Amsterdam     0.0        6.9             Clear      False        False
2    Amsterdam     0.0        6.5  Partially cloudy      False        False
3    Amsterdam     0.0        6.7  Partially cloudy      False        False
4    Amsterdam     0.0        7.4  Partially cloudy      False        False
..         ...     ...        ...               ...        ...          ...
739  Amsterdam     0.0       21.3          Overcast      False        False
740  Amsterdam     0.0       21.3          Overcast      False        False
741  Amsterdam     0.0       20.8          Overcast      False        False
742  Amsterdam     0.0       18.4          Overcast      False        False
743  Amsterdam     0.0       20.4          Overcast      False        False

[744 rows x 6 columns]

In [70]:
df1[df1['Wind_Cond']==True]

          name  precip  windspeed      conditions  Wind_Cond  Precip_Cond
79   Amsterdam   0.000       30.2        Overcast       True        False
83   Amsterdam   0.004       33.4  Rain, Overcast       True        False
84   Amsterdam   0.004       30.7  Rain, Overcast       True        False
85   Amsterdam   0.000       31.0        Overcast       True        False
91   Amsterdam   0.000       30.1        Overcast       True        False
..         ...     ...        ...             ...        ...          ...
688  Amsterdam   0.000       34.1        Overcast       True        False
689  Amsterdam   0.000       30.5        Overcast       True        False
690  Amsterdam   0.000       39.6        Overcast       True        False
691  Amsterdam   0.000       31.1        Overcast       True        False
692  Amsterdam   0.009       33.7  Rain, Overcast       True        False

[98 rows x 6 columns]

In [71]:
df1[df1['Precip_Cond']==True]

          name  precip  windspeed      conditions  Wind_Cond  Precip_Cond
165  Amsterdam   1.531       23.0  Rain, Overcast      False         True
266  Amsterdam   1.390       31.3  Rain, Overcast       True         True
267  Amsterdam   1.051       33.9  Rain, Overcast       True         True
268  Amsterdam   1.428       33.4  Rain, Overcast       True         True
269  Amsterdam   1.765       29.5  Rain, Overcast      False         True
270  Amsterdam   1.142       22.0  Rain, Overcast      False         True
271  Amsterdam   1.676       20.8  Rain, Overcast      False         True
438  Amsterdam   1.923       37.0  Rain, Overcast       True         True
439  Amsterdam   2.414       34.6  Rain, Overcast       True         True
440  Amsterdam   2.487       34.5  Rain, Overcast       True         True
441  Amsterdam   2.779       36.2  Rain, Overcast       True         True
442  Amsterdam   1.626       46.0  Rain, Overcast       True         True
445  Amsterdam   1.177       39.0  Rain, Overcast       True         True
485  Amsterdam   1.610       48.5  Rain, Overcast       True         True
502  Amsterdam   1.466       10.5  Rain, Overcast      False         True
656  Amsterdam   1.673       16.3  Rain, Overcast      False         True
657  Amsterdam   1.578       14.8  Rain, Overcast      False         True
658  Amsterdam   1.446       17.8  Rain, Overcast      False         True
659  Amsterdam   1.582       17.7  Rain, Overcast      False         True
660  Amsterdam   1.277       17.7  Rain, Overcast      False         True
678  Amsterdam   1.340       16.6  Rain, Overcast      False         True
679  Amsterdam   2.040       27.4  Rain, Overcast      False         True
680  Amsterdam   1.512       31.0  Rain, Overcast       True         True
681  Amsterdam   1.664       37.4  Rain, Overcast       True         True

In [72]:
df1

          name  precip  windspeed        conditions  Wind_Cond  Precip_Cond
0    Amsterdam     0.0        4.0             Clear      False        False
1    Amsterdam     0.0        6.9             Clear      False        False
2    Amsterdam     0.0        6.5  Partially cloudy      False        False
3    Amsterdam     0.0        6.7  Partially cloudy      False        False
4    Amsterdam     0.0        7.4  Partially cloudy      False        False
..         ...     ...        ...               ...        ...          ...
739  Amsterdam     0.0       21.3          Overcast      False        False
740  Amsterdam     0.0       21.3          Overcast      False        False
741  Amsterdam     0.0       20.8          Overcast      False        False
742  Amsterdam     0.0       18.4          Overcast      False        False
743  Amsterdam     0.0       20.4          Overcast      False        False

[744 rows x 6 columns]

In [82]:
conditions = [
    (df1['Wind_Cond'] == True) & (df1['Precip_Cond'] == False),
    (df1['Precip_Cond'] == True)  & (df1['Wind_Cond'] == False),
    (df1['Wind_Cond'] == True) &  (df1['Precip_Cond'] == True),
    (df1['Wind_Cond'] == False) &  (df1['Precip_Cond'] == False)
    ]

values = [1,2,3,4]
df1['tier'] = np.select(conditions, values)

C:\Users\sam50\AppData\Local\Temp\ipykernel_8840\2929800071.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['tier'] = np.select(conditions, values)

In [87]:
df1.iloc[250:300]

,name,precip,windspeed,conditions,Wind_Cond,Precip_Cond,tier
250,Amsterdam,0.000,22.2,Overcast,False,False,4
251,Amsterdam,0.000,20.2,Overcast,False,False,4
252,Amsterdam,0.000,27.7,Overcast,False,False,4
253,Amsterdam,0.000,26.0,Overcast,False,False,4
254,Amsterdam,0.000,31.8,Overcast,True,False,1
255,Amsterdam,0.000,30.8,Overcast,True,False,1
256,Amsterdam,0.000,28.6,Overcast,False,False,4
257,Amsterdam,0.000,28.7,Overcast,False,False,4
258,Amsterdam,0.000,28.4,Overcast,False,False,4
259,Amsterdam,0.115,33.5,"Rain, Overcast",True,False,1
260,Amsterdam,0.835,33.8,"Rain, Overcast",True,False,1
261,Amsterdam,0.759,33.6,"Rain, Overcast",True,False,1
262,Amsterdam,0.037,29.0,"Rain, Overcast",False,False,4
263,Amsterdam,0.178,33.5,"Rain, Overcast",True,False,1
264,Amsterdam,0.559,34.3,"Rain, Overcast",True,False,1
265,Amsterdam,0.800,33.7,"Rain, Overcast",True,False,1
266,Amsterdam,1.390,31.3,"Rain, Overcast",True,True,3
267,Amsterdam,1.051,33.9,"Rain, Overcast",True,True,3
268,Amsterdam,1.428,33.4,"Rain, Overcast",True,True,3
269,Amsterdam,1.765,29.5,"Rain, Overcast",False,True,2
270,Amsterdam,1.142,22.0,"Rain, Overcast",False,True,2
271,Amsterdam,1.676,20.8,"Rain, Overcast",False,True,2
272,Amsterdam,0.284,19.8,"Rain, Overcast",False,False,4
273,Amsterdam,0.000,16.5,Overcast,False,False,4
274,Amsterdam,0.075,17.4,"Rain, Overcast",False,False,4
275,Amsterdam,0.066,21.0,"Rain, Overcast",False,False,4
276,Amsterdam,0.007,26.1,Rain,False,False,4
277,Amsterdam,0.035,24.3,"Rain, Partially cloudy",False,False,4
278,Amsterdam,0.000,23.7,Partially cloudy,False,False,4
279,Amsterdam,0.185,25.8,"Rain, Partially cloudy",False,False,4
280,Amsterdam,0.014,22.3,"Rain, Partially cloudy",False,False,4
281,Amsterdam,0.056,19.0,"Rain, Partially cloudy",False,False,4
282,Amsterdam,0.000,13.6,Clear,False,False,4
283,Amsterdam,0.000,10.9,Clear,False,False,4
284,Amsterdam,0.000,10.5,Partially cloudy,False,False,4
285,Amsterdam,0.000,13.3,Partially cloudy,False,False,4
286,Amsterdam,0.014,13.4,Rain,False,False,4
287,Amsterdam,0.000,11.3,Clear,False,False,4
288,Amsterdam,0.000,13.8,Clear,False,False,4
289,Amsterdam,0.123,19.2,"Rain, Partially cloudy",False,False,4
290,Amsterdam,0.069,15.1,"Rain, Overcast",False,False,4
291,Amsterdam,0.000,27.6,Partially cloudy,False,False,4
292,Amsterdam,0.097,22.2,"Rain, Partially cloudy",False,False,4
293,Amsterdam,0.070,23.3,"Rain, Overcast",False,False,4
294,Amsterdam,0.009,23.7,"Rain, Overcast",False,False,4
295,Amsterdam,0.018,21.0,"Rain, Overcast",False,False,4
296,Amsterdam,0.000,23.3,Overcast,False,False,4
297,Amsterdam,0.000,21.0,Overcast,False,False,4
298,Amsterdam,0.000,20.8,Overcast,False,False,4
299,Amsterdam,0.000,23.6,Overcast,False,False,4

In [1]:
df1['tier'].unique()

NameError: name 'df1' is not defined

In [89]:
df1['datetime'] = df['datetime']

C:\Users\sam50\AppData\Local\Temp\ipykernel_8840\1940395164.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['datetime'] = df['datetime']

In [90]:
df1

,name,precip,windspeed,conditions,Wind_Cond,Precip_Cond,tier,datetime
0,Amsterdam,0.0,4.0,Clear,False,False,4,2021-01-01T00:00:00
1,Amsterdam,0.0,6.9,Clear,False,False,4,2021-01-01T01:00:00
2,Amsterdam,0.0,6.5,Partially cloudy,False,False,4,2021-01-01T02:00:00
3,Amsterdam,0.0,6.7,Partially cloudy,False,False,4,2021-01-01T03:00:00
4,Amsterdam,0.0,7.4,Partially cloudy,False,False,4,2021-01-01T04:00:00
...,...,...,...,...,...,...,...,...
739,Amsterdam,0.0,21.3,Overcast,False,False,4,2021-01-31T19:00:00
740,Amsterdam,0.0,21.3,Overcast,False,False,4,2021-01-31T20:00:00
741,Amsterdam,0.0,20.8,Overcast,False,False,4,2021-01-31T21:00:00
742,Amsterdam,0.0,18.4,Overcast,False,False,4,2021-01-31T22:00:00
743,Amsterdam,0.0,20.4,Overcast,False,False,4,2021-01-31T23:00:00